### ISSUE TITLE
Upgrade to Ultradom

### ISSUE THREAD

**Issue by jorgebucaran** [tcrowe/picodom-stringify#1]
Hi @tcrowe. 👋

Just a friendly heads up! [Ultradom](https://github.com/jorgebucaran/ultradom) is the continuation of and successor to Picodom. Could you upgrade your dependencies? And also update your repository's tags, i.e., ~~`picodom`~~ → `ultradom`.

**Comment by jorgebucaran** [comment]
Thank you, @tcrowe!

**Comment by tcrowe** [comment]
Got it! Thanks for pinging me on it @jorgebucaran 

https://github.com/tcrowe/hyperapp-stringify/issues/2 solved as well
